# Generated by Django 4.2.1 on 2023-05-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20230504_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='Quantity',
        ),
    ]
