# Generated by Django 3.2.10 on 2023-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_checkoutdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
