# Generated by Django 3.2.10 on 2023-06-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_userdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='usename',
            new_name='username',
        ),
    ]
