# Generated by Django 3.2.10 on 2023-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_usename_userdb_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='confirmpassword',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
